### ISSUE TITLE
Add missing `Endpoints` and `Functions`

### ISSUE THREAD

**Issue by AndreasReitberger** [AndreasReitberger/LexOfficeClientSharp#37]
Add missing `Endpoints` and `Functions` to the library

- [x] Contact.Add
- [x] Contact.Update
- [x] Countries
- [x] Payments https://github.com/AndreasReitberger/LexOfficeClientSharp/pull/30

**Comment by AlexHolly** [comment]
Is there a reason for using `double` instead of `decimal`, for example in [LexQuotationTotalPrice.cs](https://github.com/AndreasReitberger/LexOfficeClientSharp/blob/main/src/LexOfficeSharpApi/Model/Quotation/LexQuotationTotalPrice.cs)?

It is generally recommended to use `decimal` in financial systems to avoid precision issues.

**Comment by AndreasReitberger** [comment]
No, I'm just used to use `double` in my classes. I will switch to `decimal` then ;) Thanks for the hint!
